# Codecov YAML
# https://docs.codecov.com/docs/codecovyml-reference

codecov:
  branch: main

coverage:
  status:
    project:
      default:
        target: auto
        threshold: 0%
    patch:
      default:
        target: auto
        threshold: 0%
