# Pre-commit
# https://pre-commit.com

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: "v4.6.0"
    hooks:
      - id: check-json
      - id: check-merge-conflict
      - id: check-toml
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: "v4.0.0-alpha.8"
    hooks:
      - id: prettier
        args:
          - --no-error-on-unmatched-pattern
  - repo: https://github.com/DavidAnson/markdownlint-cli2
    rev: "v0.14.0"
    hooks:
      - id: markdownlint-cli2
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: "v0.6.8"
    hooks:
      - id: ruff
      - id: ruff-format
        args:
          - --diff
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: "v1.11.2"
    hooks:
      - id: mypy
        additional_dependencies:
          - django-stubs[compatible-mypy] < 6
          - openpyxl < 4
          - psycopg2-binary < 3
          - python-dotenv < 2
          - types-openpyxl < 4
