name: "Pre-commit: Run"

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  pre-commit-run:
    if: ${{ !startsWith(github.event.head_commit.message, 'bump:') }}
    name: Run Pre-commit hooks
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
      - uses: pre-commit/action@v3.0.1
