name: "Pre-commit: Update"

on:
  schedule:
    - cron: 0 0 * * 1

jobs:
  pre-commit-update:
    name: Update Pre-commit hooks
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          cache: pip
      - run: python -m pip install --upgrade pip
      - run: python -m pip install pre-commit
      - run: pre-commit autoupdate
      - uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ secrets.CREATE_PR_ACTION_TOKEN }}
          branch: chore/pre-commit-update
          commit-message: "chore(deps): update Pre-commit hooks"
          title: "chore(deps): update Pre-commit hooks"
          body: |
            Automated changes by [@peter-evans/create-pull-request](https://github.com/peter-evans/create-pull-request) action.
