name: "Python: CD"

on:
  push:
    tags:
      - "*.*.*"

jobs:
  build:
    name: Build package
    runs-on: ubuntu-latest
    outputs:
      package-version: ${{ steps.package-version.outputs.package-version }}
    steps:
      - uses: actions/checkout@v7.0.1
      - uses: astral-sh/setup-uv@v9.0.0
        with:
          enable-cache: true
      - run: uv build
      - uses: actions/upload-artifact@v7.0.1
        with:
          name: dist
          path: dist/*
      - id: package-version
        run: |
          uv sync --locked --no-dev
          echo "package-version=$(
            uv run python -c 'import sys, xlsx_serializer; sys.stdout.write(xlsx_serializer.__version__)'
          )" >> $GITHUB_OUTPUT
  check-tag:
    name: Check tag
    needs:
      - build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7.0.1
      - run: |
          if [ "${{ needs.build.outputs.package-version }}" != "${{ github.ref_name }}" ]; then
            exit 1
          fi
  pypi:
    name: Publish package to PyPI
    needs:
      - check-tag
    runs-on: ubuntu-latest
    permissions:
      id-token: write
    environment:
      name: PyPI
      url: https://pypi.org/p/django-xlsx-serializer/
    steps:
      - uses: actions/download-artifact@v8.0.1
        with:
          name: dist
          path: dist/
      - uses: pypa/gh-action-pypi-publish@v1.14.2
  release:
    name: Create GitHub release
    needs:
      - pypi
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v7.0.1
      - uses: softprops/action-gh-release@v3.0.2
        with:
          generate_release_notes: true
